#include "faces.h"

const int8_t nextFaces[][3] = {
  {UNSURE, INVALID_FACE, INVALID_FACE}, // AHEGAO
  {UNSURE, AHEGAO, INVALID_FACE}, // COLD
  {OWO, SPEECHLESS, INVALID_FACE}, // CONFUSED
  {FROWN, INVALID_FACE, INVALID_FACE}, // DEAD
  {DEAD, SPEECHLESS, INVALID_FACE}, // FROWN
  {HAPPY, UWU, OWO}, // GLAD
  {HAPPY, SPEECHLESS, POLITE}, // GRIN
  {GLAD, SURPRISED, GRIN}, // HAPPY
  {SURPRISED, INVALID_FACE, INVALID_FACE}, // HOT
  {UWU, GLAD, CONFUSED}, // OWO
  {GRIN, UNSURE, INVALID_FACE}, // POLITE
  {DEAD, AHEGAO, INVALID_FACE}, // SHOCK
  {FROWN, CONFUSED, GRIN}, // SPEECHLESS
  {HAPPY, INVALID_FACE, INVALID_FACE}, // SURPRISED
  {POLITE, AHEGAO, INVALID_FACE}, // UNSURE
  {OWO, GLAD, INVALID_FACE} // UWU
};
