#define NUMBER_FACES 16
#define INVALID_FACE -1
#define AHEGAO 0
#define COLD 1
#define CONFUSED 2
#define DEAD 3
#define FROWN 4
#define GLAD 5
#define GRIN 6
#define HAPPY 7
#define HOT 8
#define OWO 9
#define POLITE 10
#define SHOCK 11
#define SPEECHLESS 12
#define SURPRISED 13
#define UNSURE 14
#define UWU 15

const int8_t nextFaces[][3] = {
  {UNSURE, INVALID_FACE, INVALID_FACE}, // AHEGAO
  {UNSURE, AHEGAO, INVALID_FACE}, // COLD
  {OWO, SPEECHLESS, INVALID_FACE}, // CONFUSED
  {FROWN, INVALID_FACE, INVALID_FACE}, // DEAD
  {DEAD, SPEECHLESS, INVALID_FACE}, // FROWN
  {HAPPY, UWU, OWO}, // GLAD
  {HAPPY, SPEECHLESS, POLITE}, // GRIN
  {GLAD, SURPRISED, GRIN}, // HAPPY
  {SURPRISED, INVALID_FACE, INVALID_FACE}, // HOT
  {UWU, GLAD, CONFUSED}, // OWO
  {GRIN, UNSURE, INVALID_FACE}, // POLITE
  {DEAD, AHEGAO, INVALID_FACE}, // SHOCK
  {FROWN, CONFUSED, GRIN}, // SPEECHLESS
  {HAPPY, INVALID_FACE, INVALID_FACE}, // SURPRISED
  {POLITE, AHEGAO, INVALID_FACE}, // UNSURE
  {OWO, GLAD, INVALID_FACE} // UWU
};
